"""nxopen/generate_cam_from_selection.py

NXOpen journal to generate CAM operations from selected_tools.json.
Run inside NX: File -> Execute -> Journal -> select this file -> Run

Notes:
- This script is a template/poc. NXOpen CAM APIs differ by NX version and installed CAM modules.
- The script attempts to create simple drilling and milling operations based on
  input/output files generated by the tool_selector.
- You MUST inspect the created operations and run CAM Simulation in NX before
  post-processing to G-code. Never run generated G-code on a machine without
  prior verification.

Inputs (relative to repo root):
  output/selected_tools.json  -- selected tool candidates (you confirmed selection)
  input/candidates.json       -- feature list (geom, types)
  output/toollib_standard.json -- normalized tool library

Outputs:
  output/nx_cam_journal_run.log  -- plain text run log from this journal
  output/generated_gcode.nc      -- placeholder for generated G-code (post output)

Usage:
  1) Ensure you placed selected_tools.json in repo/output (or update paths below).
  2) In NX: File -> Execute -> Journal -> select this file -> Run.

Important: This file contains best-effort NXOpen API calls and FALLBACK stubs
for environments without CAM or a different NXOpen API surface. If an API
call raises, the script prints an explanation to the NX log and writes a
lightweight JSON summary to output/.
"""

import os
import json
import traceback

REPO_ROOT = os.path.join(os.path.dirname(__file__), '..')
SELECTED_PATH = os.path.join(REPO_ROOT, 'output', 'selected_tools.json')
CANDIDATES_PATH = os.path.join(REPO_ROOT, 'input', 'candidates.json')
TOOLLIB_PATH = os.path.join(REPO_ROOT, 'output', 'toollib_standard.json')
LOG_PATH = os.path.join(REPO_ROOT, 'output', 'nx_cam_journal_run.log')
GCODE_OUT = os.path.join(REPO_ROOT, 'output', 'generated_gcode.nc')


def write_log(s):
    with open(LOG_PATH, 'a', encoding='utf-8') as f:
        f.write(s + '\n')
    print(s)


try:
    import NXOpen
    import NXOpen.CAM
    NX_AVAILABLE = True
except Exception as e:
    NX_AVAILABLE = False
    write_log('NXOpen not available in this environment: ' + str(e))


def load_json(p):
    try:
        with open(p, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        write_log(f'Failed to load JSON {p}: {e}')
        return None


def create_drill_operations(session, part, cam_session, selected, candidates):
    """Best-effort creation of drilling operations.
    Adapt to your NX/CAM API if methods differ.
    """
    write_log('Attempting to create drill operations...')
    try:
        # The NXOpen.CAM API surface is large and installation dependent.
        # This placeholder demonstrates intent: iterate features and create
        # a simple drilling operation with chosen tool ID as a reference.
        for feat in candidates:
            if feat['feature_type'] != 'hole':
                continue
            fid = feat['id']
            sel = next((s for s in selected if s['feature_id'] == fid), None)
            if not sel:
                write_log(f'No selected tool for feature {fid}, skipping')
                continue
            tool_id = sel['selected']
            # Pseudo: create operation
            write_log(f'Would create drill op for {fid} with tool {tool_id}')
            # Real code would create NX CAM objects here.
        write_log('Drill operation creation (placeholder) complete.')
    except Exception:
        write_log('Exception while creating drill operations:')
        write_log(traceback.format_exc())


def create_mill_operations(session, part, cam_session, selected, candidates):
    write_log('Attempting to create milling operations...')
    try:
        for feat in candidates:
            if feat['feature_type'] in ('pocket', 'profile', 'slot'):
                fid = feat['id']
                sel = next((s for s in selected if s['feature_id'] == fid), None)
                if not sel:
                    write_log(f'No selected tool for feature {fid}, skipping')
                    continue
                tool_id = sel['selected']
                write_log(f'Would create mill op for {fid} with tool {tool_id}')
        write_log('Mill operation creation (placeholder) complete.')
    except Exception:
        write_log('Exception while creating mill operations:')
        write_log(traceback.format_exc())


def run():
    write_log('NX CAM generation journal started')
    selected = load_json(SELECTED_PATH) or []
    candidates = load_json(CANDIDATES_PATH) or []
    toollib = load_json(TOOLLIB_PATH) or {}

    if not NX_AVAILABLE:
        write_log('NX not available: generating summary output only.')
        # Produce a small summary JSON pointing to chosen tools
        summary = {'selected_tools_summary': selected}
        outp = os.path.join(REPO_ROOT, 'output', 'nx_cam_summary.json')
        with open(outp, 'w', encoding='utf-8') as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        write_log('Wrote summary to ' + outp)
        write_log('To generate full CAM operations, run this journal inside NX with CAM module available.')
        return

    try:
        session = NXOpen.Session.GetSession()
        work_part = session.Parts.Work
        display_part = session.Parts.Display
        write_log('NX session detected. Work part: ' + (work_part.Name if work_part else 'None'))
        # Attempt to get CAM session
        try:
            cam_session = NXOpen.CAM.CAMSession.GetSession(work_part)
        except Exception:
            cam_session = None
            write_log('CAMSession not available or failed to initialize')

        # Create drill ops
        create_drill_operations(session, work_part, cam_session, selected, candidates)
        # Create mill ops
        create_mill_operations(session, work_part, cam_session, selected, candidates)

        # Post-processing placeholder: user must run NX post builder to generate G-code
        write_log('CAM creation placeholder complete. Please open the part in NX CAM and run post-process to generate G-code (Fanuc Oi).')

    except Exception:
        write_log('Unexpected exception in journal:')
        write_log(traceback.format_exc())


if __name__ == '__main__':
    run()
